# This file sets the configuration of the main menu. If your backend is simple,
# you probably can leave the 'menu' option empty and rely on the default menu
# created by EasyAdmin.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at
easy_admin:
    design:
        menu:
            - label: 'Menu Gestion'
              icon: 'th-list'
              children:
                  - { entity: 'User', icon: 'female', label: 'Hôtesse', params: { sortField: 'createdAt' }, default: true }
                  - { entity: 'Evenement', icon: 'calendar', label: 'Événement' }
            - { label: 'Recherche avancé', url: 'http://2.ip-164-132-99.eu/my_project/web/app_dev.php/recherchesansdispo', icon: 'search', target: '_blank' }
            - { label: 'Recherche avec dispo', url: 'http://2.ip-164-132-99.eu/my_project/web/app_dev.php/rechercheavecdispo', icon: 'search', target: '_blank' }
            - { label: 'Créé par Pierre Flamant' }